# Generated by Django 5.1.2 on 2024-11-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='info',
            field=models.JSONField(default=dict),
        ),
    ]
