# Generated by Django 5.1.2 on 2024-11-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_file_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default='documents/default_file.txt', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
