# Generated by Django 5.1.2 on 2024-11-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='active_projects',
            field=models.JSONField(default=dict),
        ),
    ]
