# Generated by Django 5.1.2 on 2024-11-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_active_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='staff',
            new_name='employee',
        ),
    ]
