# Generated by Django 5.1.2 on 2024-11-03 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_profile_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='client_since',
            new_name='member_since',
        ),
    ]
