# Generated by Django 5.1.2 on 2024-11-03 21:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_client_since_customuser_member_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='member_since',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
