# Generated by Django 5.1.2 on 2024-11-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_member_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='files',
            field=models.JSONField(default=dict),
        ),
    ]
